title: Junping Li's Homepage
page-top-title: Junping Li
top-section-bg-text: Clinical Medicine
home-subtitle: Junping Li&ensp;|&ensp;李军平
copyright-text: '&copy; Junping Li 2023-2025. All Rights Reserved.'
